name: CI/CD Pipeline for ASP.NET Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # CHẠY TRÊN WINDOWS

    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v3

      - name: 🏗 Setup .NET Framework
        run: |
          choco install dotnetfx --version=4.7.2  # Cài đặt .NET Framework 4.7.2
          choco install dotnet-sdk --version=8.0.406  # Đảm bảo có .NET SDK 8.0

      - name: 📦 Restore dependencies
        run: dotnet restore SOF205_ASS/SOF205_ASS/QLBanHang/QLBanVeXemPhim.sln

      - name: 🚀 Build project
        run: dotnet build SOF205_ASS/SOF205_ASS/QLBanHang/QLBanVeXemPhim.sln --configuration Release

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v3

      - name: 🏗 Setup .NET Framework
        run: |
          choco install dotnetfx --version=4.7.2  # Cài đặt .NET Framework 4.7.2

      - name: 📦 Restore dependencies
        run: dotnet restore SOF205_ASS/SOF205_ASS/QLBanHang/QLBanVeXemPhim.sln

      - name: 🧪 Run Unit Tests
        run: dotnet test SOF205_ASS/SOF205_ASS/QLBanHang/QLBanVeXemPhim.sln --configuration Release

  deploy:
    runs-on: windows-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy Application
        run: |
          echo "Bắt đầu deploy..."
          # Thêm lệnh deploy theo môi trường của bạn (Azure, AWS, VPS, ...)
