name: CI/CD Pipeline for ASP.NET Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Chạy trên Windows

    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v3

      - name: 🏗 Install .NET Framework Developer Pack
        run: choco install netfx-4.7.2-devpack -y  # Cài đặt Developer Pack 4.7.2

      - name: 🏗 Install MSBuild Tools
        run: |
          choco install visualstudio2019-buildtools --params "--add Microsoft.VisualStudio.Workload.MSBuildTools" -y
          refreshenv  # Load lại biến môi trường

      - name: 📦 Restore dependencies
        run: dotnet restore SOF205_ASS/SOF205_ASS/QLBanHang/QLBanVeXemPhim.sln

      - name: 🚀 Build project using MSBuild
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" SOF205_ASS/SOF205_ASS/QLBanHang/QLBanVeXemPhim.sln /p:Configuration=Release /p:Platform=x64

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v3

      - name: 🏗 Install .NET Framework Developer Pack
        run: choco install netfx-4.7.2-devpack -y  # Cài đặt Developer Pack 4.7.2

      - name: 🏗 Install MSBuild Tools
        run: |
          choco install visualstudio2019-buildtools --params "--add Microsoft.VisualStudio.Workload.MSBuildTools" -y
          refreshenv

      - name: 📦 Restore dependencies
        run: dotnet restore SOF205_ASS/SOF205_ASS/QLBanHang/QLBanVeXemPhim.sln

      - name: 🧪 Run Unit Tests
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" SOF205_ASS/SOF205_ASS/QLBanHang/QLBanVeXemPhim.sln /p:Configuration=Release /p:Platform=x64
          dotnet test SOF205_ASS/SOF205_ASS/QLBanHang/QLBanVeXemPhim.sln --configuration Release

  deploy:
    runs-on: windows-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy Application
        run: |
          echo "Bắt đầu deploy..."
          # Thêm lệnh deploy theo môi trường của bạn (Azure, AWS, VPS, ...)
