name: CI/CD Pipeline for ASP.NET Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v3

      - name: 🏗 Install .NET Framework Developer Pack
        run: choco install netfx-4.7.2-devpack -y

      - name: 🏗 Install Visual Studio Build Tools 2022
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_BuildTools.exe" -OutFile "vs_BuildTools.exe"
          Start-Process -FilePath "vs_BuildTools.exe" -ArgumentList "--quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Workload.MSBuildTools" -NoNewWindow -Wait
        shell: powershell

      - name: 🔍 Find MSBuild Path
        id: find-msbuild
        shell: powershell
        run: |
          # Tìm tất cả MSBuild.exe
          $MSBuildPaths = vswhere -latest -requires Microsoft.Component.MSBuild -find **\MSBuild.exe

          # Nếu có nhiều MSBuild.exe, chọn cái đầu tiên
          if ($MSBuildPaths -is [array]) {
            $MSBuildPath = $MSBuildPaths[0]
          } else {
            $MSBuildPath = $MSBuildPaths
          }

          # Kiểm tra nếu không tìm thấy MSBuild
          if (-not $MSBuildPath) {
            Write-Host "❌ Không tìm thấy MSBuild.exe! Kiểm tra lại cài đặt."
            exit 1
          }

          Write-Host "✅ Đã tìm thấy MSBuild tại: $MSBuildPath"
          echo "MSBUILD_PATH=$MSBuildPath" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: 📦 Restore dependencies
        run: dotnet restore SOF205_ASS/SOF205_ASS/QLBanHang/QLBanVeXemPhim.sln

      - name: 🚀 Build project using MSBuild
        run: |
          & "$(echo $env:MSBUILD_PATH)" SOF205_ASS/SOF205_ASS/QLBanHang/QLBanVeXemPhim.sln /p:Configuration=Release /p:Platform="Any CPU"
