name: CI/CD Pipeline for ASP.NET Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v3

      - name: 🏗 Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: 📦 Restore dependencies
        run: dotnet restore

      - name: 🚀 Build project
        run: dotnet build --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v3

      - name: 🏗 Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: 📦 Restore dependencies
        run: dotnet restore

      - name: 🧪 Run Unit Tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 🛎 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy Application
        run: |
          echo "Bắt đầu deploy..."
          # Thêm lệnh deploy nếu cần (Azure, AWS, VPS, ...)

